---
title: "week 5 - class 1 - Statistics! - Correlations and simple linear regression"
author: "Phileas Dazeley Gaist"
date: "10/12/2021"
output: 
  html_document:
    df_print: paged
    keep_md: true
---

```{r}
# # ---------------------------------------------------------------
# ┏━━━┓╋╋┏┓┏┓╋╋╋╋╋╋╋╋╋╋╋╋╋╋┏━┓╋┏┓┏┓╋╋╋╋╋┏━━━┓┏┓┏┓╋╋╋╋╋╋┏┓
# ┃┏━┓┃╋╋┃┃┃┃╋╋╋╋╋╋╋╋╋╋╋╋╋╋┃┏┛┏┛┗┫┃╋╋╋╋╋┃┏━┓┣┛┗┫┃╋╋╋╋╋┏┛┗┓
# ┃┃╋┗╋━━┫┃┃┃┏━━┳━━┳━━┓┏━━┳┛┗┓┗┓┏┫┗━┳━━┓┃┃╋┃┣┓┏┫┃┏━━┳━╋┓┏╋┳━━┓
# ┃┃╋┏┫┏┓┃┃┃┃┃┃━┫┏┓┃┃━┫┃┏┓┣┓┏┛╋┃┃┃┏┓┃┃━┫┃┗━┛┃┃┃┃┃┃┏┓┃┏┓┫┃┣┫┏━┛
# ┃┗━┛┃┗┛┃┗┫┗┫┃━┫┗┛┃┃━┫┃┗┛┃┃┃╋╋┃┗┫┃┃┃┃━┫┃┏━┓┃┃┗┫┗┫┏┓┃┃┃┃┗┫┃┗━┓
# ┗━━━┻━━┻━┻━┻━━┻━┓┣━━┛┗━━┛┗┛╋╋┗━┻┛┗┻━━┛┗┛╋┗┛┗━┻━┻┛┗┻┛┗┻━┻┻━━┛
# ╋╋╋╋╋╋╋╋╋╋╋╋╋╋┏━┛┃
# ╋╋╋╋╋╋╋╋╋╋╋╋╋╋┗━━┛       Applied Data Science I - Week 5, Class 1
# # ---------------------------------------------------------------
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Today we are going to talk about correlations, correlation tests, and simple linear regressions.

# Correlations are measures of linear relationships between two variables. They can be positive or negative: positive == both variables increase or decrease together, negative == as one variable increases, the other decreases.

# Regression is about assessing how much of the variance in A explains the variance in B.

library(tidyverse)

data("diamonds")
diamonds

# This is a pretty popular  dataset containing the prices and other attributes of almost 54,000 diamonds. 

# The variables are as follows:
#
# price (in US dollars)
#
# carat (weight of the diamond)
#
# cut (quality of the cut)
#
# color (diamond color - d is best, j is worst)
#
# clarity (l1 is worst, IF is best)
# 
# x - length
# y - width 
# z - depth 
# depth = total depth percentage 
#
# table - width fo the top of the diamond relative to widest point 
```

```{r}
# # ---------------------------------------------------------------
#
# Correlations and correlation test
#
# # ---------------------------------------------------------------

# Do we think the price of a diamond and the carat (weight) are correlated? 

cor(diamonds$carat, diamonds$price)
# cor(x = diamonds$carat, y = diamonds$price)

# Let's visualize this (don't worry - we'll cover more of this next week!)

diamonds %>% 
  ggplot(aes(x = carat, y = price, color = price)) + 
  geom_point() + 
  theme_bw()

# Pretty clear that there is a relationship here, at least visually and based on this 
# point estimate! Let's test it! Let's test if the correlation is different from zero (i.e., two-sided test)
# with a 95% confidence threshold

cor.test(diamonds$carat, diamonds$price, alternative = "two.sided",conf.level = 0.95)
```

```{r}
# # ---------------------------------------------------------------
#
# Your turn! 
#
# # ---------------------------------------------------------------

# Test if there is a statistically significant correlation between price and x - the diamond's length.
# Use a 90% confidence threshold. 

cor.test(diamonds$x, diamonds$price, alternative = "two.sided",conf.level = 0.95)

# Test if there is a statistically significant correlation between the natural log of price and the natural log of carat. Use a confidence level of 0.95. Run the same visualization code above to generate a plot of these transformed variables and discuss how these plots are different. 

cor.test(log(diamonds$carat), log(diamonds$price), alternative = "two.sided", conf.level = 0.95)

diamonds %>% 
  ggplot(aes(x = log(carat), y = log(price), color = log(price))) + 
  geom_point() + 
  geom_smooth(method = "lm")
  theme_bw()
```

```{r}
# # ---------------------------------------------------------------
#
# Simple Linear Regression 
#
# # ---------------------------------------------------------------

# If a correlation is telling you how strong a linear relationship in between two variables is.
# A linear regression tells you how much of the variance in y is being explained by the variance in x.

# Let's build a simple linear model where we see how much of the variation in price
# is determined by the variation in carat! 

# ?lm
# "~" == based upon 
model_1 <- lm(price ~ carat, data = diamonds)
model_1
summary(model_1)
# REPORT ADJUSTED R^2. 

# Let's see if our linearized (log!) relationship is a better fit! 

model_2 <-lm(log(price) ~ log(carat), data = diamonds)
summary(model_2)

plot(model_2)
# residuals vs fitted plot 
# normal plot lets you know if your data is normal
# scale-location plot lets you know if there are outliers pulling your model around
# residual vs leverage plot
```

```{r}
# # ---------------------------------------------------------------
#
# Your turn!
#
# # ---------------------------------------------------------------


# Build a simple linear model between x and price. Explore whether or not you should take the log values of either variable and explain your reasoning.

cor.test(diamonds$x, diamonds$price, alternative = "two.sided",conf.level = 0.95)

diamonds %>% 
  ggplot(aes(x = x, y = price, color = price)) + 
  geom_point() + 
  
  theme_bw()

cor.test(log(diamonds$x), log(diamonds$price), alternative = "two.sided",conf.level = 0.95)

diamonds %>% 
  ggplot(aes(x = log(x), y = log(price), color = price)) + 
  geom_point() + 
  theme_bw()

# We should use log of price to perform linear regression and get a better model fit.

model_3 <- lm(x ~ log(price), data = diamonds)
model_3
summary

plot(model_3)
```

