---
title: "week 2 - class 2 - Data sets"
author: "Phileas Dazeley Gaist"
date: "9/24/2021"
output: 
  html_document:
    df_print: paged
    keep_md: true
---

```{r}
# # ---------------------------------------------------------------
# ┏━━━┓╋╋┏┓┏┓╋╋╋╋╋╋╋╋╋╋╋╋╋╋┏━┓╋┏┓┏┓╋╋╋╋╋┏━━━┓┏┓┏┓╋╋╋╋╋╋┏┓
# ┃┏━┓┃╋╋┃┃┃┃╋╋╋╋╋╋╋╋╋╋╋╋╋╋┃┏┛┏┛┗┫┃╋╋╋╋╋┃┏━┓┣┛┗┫┃╋╋╋╋╋┏┛┗┓
# ┃┃╋┗╋━━┫┃┃┃┏━━┳━━┳━━┓┏━━┳┛┗┓┗┓┏┫┗━┳━━┓┃┃╋┃┣┓┏┫┃┏━━┳━╋┓┏╋┳━━┓
# ┃┃╋┏┫┏┓┃┃┃┃┃┃━┫┏┓┃┃━┫┃┏┓┣┓┏┛╋┃┃┃┏┓┃┃━┫┃┗━┛┃┃┃┃┃┃┏┓┃┏┓┫┃┣┫┏━┛
# ┃┗━┛┃┗┛┃┗┫┗┫┃━┫┗┛┃┃━┫┃┗┛┃┃┃╋╋┃┗┫┃┃┃┃━┫┃┏━┓┃┃┗┫┗┫┏┓┃┃┃┃┗┫┃┗━┓
# ┗━━━┻━━┻━┻━┻━━┻━┓┣━━┛┗━━┛┗┛╋╋┗━┻┛┗┻━━┛┗┛╋┗┛┗━┻━┻┛┗┻┛┗┻━┻┻━━┛
# ╋╋╋╋╋╋╋╋╋╋╋╋╋╋┏━┛┃
# ╋╋╋╋╋╋╋╋╋╋╋╋╋╋┗━━┛       Applied Data Science I - Week 2, Class 2
# # ---------------------------------------------------------------
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# # ---------------------------------------------------------------
# Let's Check out some DATA
# # ---------------------------------------------------------------

# Let's load in some data that comes with R 
?data

data()

data(iris) # this is actually a really famous data set. This command loads the iris data set into your global environment
?iris

View(iris) # opens the data in a new tab, views the data. NOTE THE UPPERCASE V.
# view(iris) # will return an error 

# Always visualise your data sets, it will be super helpful down the line. 

dim(iris) # returns the dimensions of the data set: [elements, columns]
names(iris) # returns the names of the columns of the data set

str(iris) # returns the structure of the data set (tells you all sorts of stuff about the data sets)

summary(iris) # takes in a data frame and returns a bunch of aggregated statistics about the data frame. It essentially gives you a box plot of every column. (mean of column, largest, smallest value, media, 1st and 3rd quartile)

sum(is.na(iris)) # returns the number of NA elements in a data set

plot(iris) # plots all columns of the data set against each other (good for visualising relationships)

# cool, okay, we'll leave iris alone for now and come back to it! 

data(uspop) # populations recorded by the US census (This is not a dataframe, it is a time series)

View(uspop)

str(uspop)

plot(uspop)
```

```{r}
# # ---------------------------------------------------------------
# Let's import some data!
# # ---------------------------------------------------------------

# If this is the first time you do this, you'll want to run this command! 
# install.packages("tidyverse")

library(tidyverse) # "the most useful package ever" according to Kyle: Tidyverse is a huge set of tools to make data science easier and more straightforward. It is a bit like a sub-language of R. It is a library that imports other libraries to your projects to work with. 

?tidyverse

# Let's read in some Bob Ross Data! 

bob_ross_data <- read_csv(url("https://raw.githubusercontent.com/fivethirtyeight/data/master/bob-ross/elements-by-episode.csv")) # read a csv file from the internet
?url
?read_csv

str(bob_ross_data)
?tibble # A tibble is a dataframe, but if you subset it, you always get a tibble back

View(bob_ross_data)

sum(is.na(bob_ross_data))
```

```{r}
# --------------------------------------------------
# Let's answer a few questions about this data set!
# --------------------------------------------------

# How many episodes are there? There are several approaches to solving the problem:

dim(bob_ross_data)[1]
length(bob_ross_data$EPISODE)

# How many episodes contained at least one tree? There are several approaches to solving the problem:

sum(bob_ross_data$TREE)

# What percentage of episodes contained exactly one tree? 

sum(bob_ross_data$TREE) / length(bob_ross_data$EPISODE)

# What percentage of episodes contained at least two trees? 

sum(bob_ross_data$TREES) / length(bob_ross_data$EPISODE)

# What is the most common element in Joy of Painting? 

sort(colSums(bob_ross_data[,-c(1,2)]), decreasing = TRUE)

# View(bob_ross_data[,-c(1,2)]) # returns and views the data set without the first two columns
# View(bob_ross_data[,-c(1,2)]) # returns and views only the first two columns of the data frame
# View(bob_ross_data[c(1,)]) # returns and views only the first two rows of the data frame
# colSums() # returns the sum of columns of a data frame

# The following two commands return the same thing:

bob_ross_data[,2]
bob_ross_data$TITLE
```

```{r}
# Given that Bob Ross painted a single tree, what's the likelihood that he also painted clouds? 
#
# Remember (or learn!) the rule for conditional probability: 
# 
# P(A and B) = P(A)*P(B|A) 
#
# P(A) = Probability that A happened
# P(A and B) = Probability that A and B happened
# P(B|A) = Probability that B happened GIVEN that A happened
#
# rewrite it ....
#
# P(B|A) = P(A and B) / P(A) 

# probability of episodes of bob ross where bob paints a single tree
percentage_trees = sum(bob_ross_data$TREE) / length(bob_ross_data$EPISODE)

# probability of episodes of bob ross where bob paints clouds
percentage_clouds = sum(bob_ross_data$CLOUDS) / length(bob_ross_data$EPISODE)

# episodes of bob ross where bob paints a single tree and clouds
trees_and_clouds <- bob_ross_data %>% 
  filter(bob_ross_data$TREE == 1 & bob_ross_data$CLOUDS == 1)

# The pipe operator is useful because it allows you to get a changed version of something without making changes to the original.

# %>% is the "pipe" operator and let's you "chain" steps together (ctrl+shift+m)
# filter() is a function that says "keep only the rows where these things are true 
# & is a logical operator for "AND". | is the logical operator for "OR" 

dim(trees_and_clouds)
dim(bob_ross_data)

# proportion of bob ross episodes where bob paints a single tree and clouds
percentage_trees_and_clouds = length(trees_and_clouds$EPISODE) / length(bob_ross_data$EPISODE)

# probability of an episode of bob ross showing bob draw a cloud given that he also draws a single tree.
(final_answer <- percentage_trees_and_clouds / percentage_trees)

# NOTE: If you wrap a variable in (), it will display the variable when you execute it!
```

```{r}
# EXERCISE: Given that Bob Ross painted clouds, what's the likelihood that he also painted a conifer?

prob_conifer <- sum(bob_ross_data$CONIFER / length(bob_ross_data$EPISODE))

# episodes of bob ross where bob paints a single tree and a conifer
conifer_and_clouds <- bob_ross_data %>% 
  filter(bob_ross_data$CLOUDS == 1 & bob_ross_data$CONIFER == 1)

# proportion of bob ross episodes where bob paints a single tree and clouds
prop_conifer_and_clouds = length(conifer_and_clouds$EPISODE) / length(bob_ross_data$EPISODE)

# probability of an episode of bob ross showing bob draw a conifer given that he also draws a cloud
(final_answer <- prop_conifer_and_clouds / prob_conifer)
```

```{r}
# # ---------------------------------------------------------------
# Let's import some other data! 
# # ---------------------------------------------------------------
library(readxl)
# install.packages("readxl")

climate_change_data <- readxl::read_xls("/Users/phileasdazeleygaist/Desktop/Applied-Data-Science-Fall_2020-COA/Data/climate_change_download_0.xls")

climate_change_data

climate_change_data %>% 
  # This selects the data sets and says "prepare to do more with it" by using %>% 
  select(`Series name`) %>%
  # This command says "Select just this column" and "prepare to do more" by using the %>% 
  distinct() %>% 
  # This says "please only show me the unique values in here and "prepare to do more" by using the %>% 
  View()
  # This opens the View port so you can take a peek 


# Can we you select and filter for JUST The data in the United States that contains CO2 emissions per capita (metric tons)? 

climate_change_data %>% 
  filter(`Series name` == 'CO2 emissions per capita (metric tons)',
         `Country name` == 'United States')


# Let's save this 

us_emissions <- climate_change_data %>% 
  filter(`Series name` == 'CO2 emissions per capita (metric tons)',
         `Country name` == 'United States')

View(us_emissions)

# Let's do some cleaning! To make our lives easier, let's use the janitor package! 
library(janitor)
# install.packages("janitor")

us_emissions_cleaned <- us_emissions %>%
  clean_names() %>%
  select(-c(country_code, country_name, series_code, scale, decimals, series_name)) %>% 
  gather(year, value) %>%
  mutate(year = as.integer(str_replace(year, "[^\\d]", ""))) %>%
  filter(year < 2009)


plot(us_emissions_cleaned)
```




